### ISSUE TITLE
Model not working with the script

### ISSUE THREAD

**Issue by andimi** [MaxJakobs/SegButler#3]
I tested the script with these three models available in our dropbox/Models/Cells/ folder:

- [x] deepGlass_objSz30_SKrusoe_Organoids_OG_Cells_crop240_seed1759Sat_27_Mar_2021_07-17-46
- [x] deepGlass_objSz15_SKrusoe_Organoids_OG_Cells_crop112_seed7741Wed_24_Mar_2021_22-23-28
- [ ] deepGlass_objSz15_SKrusoe_Organoids_crop160_seed8992Fri_26_Mar_2021_01-28-15

The last one didn't generate a results folder but didn't throw an error.

**Comment by andimi** [comment]
Also, using the test image, the deepGlass_objSz15_SKrusoe_Organoids_OG_Cells_crop112_seed7741Wed_24_Mar_2021_22-23-28 seemed to work better.

**Comment by MaxJakobs** [comment]
yeah th 26 march net doesn't give anything
