### ISSUE TITLE
Overlay and binary size and display error

### ISSUE THREAD

**Issue by andrea-dimitracopoulos** [MaxJakobs/SegButler#5]
When running the script on a full stack of images I noticed these errors:

**Binary**
The size of the images seem wrong, i.e. the x and y dimensions seem swapped:
![image](https://user-images.githubusercontent.com/3579760/114270552-e8ba4400-9a04-11eb-8c48-fc5a035e9162.png)

**Overlays and Binary**
The results don't overlay properly with the data:
![image](https://user-images.githubusercontent.com/3579760/114270452-5d40b300-9a04-11eb-9a53-3e3f5ce4e35d.png)

This happens using both networks with object size 30 and 15 

This is the code used to generate the results:
`wolframscript -script ./scripts/runSegButler.wls -imgdir ./testdata/unlabelled/ -objSz 120 -imgstacks`

With the unlabelled folder containing Sophie's files (full stacks). The particular example comes from 
Slide_4_72hr_naive_E-cadherin_Beta-catenin_TCF3_1_MMStack_Default_xy_0-1319_z_0-5.ome.tif, slice 60.

**Comment by MaxJakobs** [comment]
fixed in latest commit
